'THIS PROGRAM PRINTS THE SUM OF 10 NUMBERS THAT ARE DIVISIBLE BY 5 AND 3
'AND THE PRODUCT OF THE NUMBERS ONLY DIVISIBLE BY 5
LET SUM1 = 0
LET PROD1 = 1
FOR X = 1 TO 10
    INPUT "ENTER A NUMBER"; INP1

    IF INP1 MOD 5 = 0 AND INP1 MOD 3 = 0 THEN
        LET SUM1 = SUM1 + INP1
    ELSEIF INP1 MOD 5 = 0 AND INP1 <> 0 THEN
        LET PROD1 = PROD1 * INP1
    END IF
NEXT X
PRINT "SUM IS:"; SUM1
PRINT "PRODUCT IS:"; PROD1
END
